### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by aeksco** [CottageLabs/facetview2#17]
This repository should have a license attached to it. I've would like to fork this codebase for another project but without a proper license I'm not _technically_ in a legal position to do so:

[Github - Open-Source Licensing](https://help.github.com/articles/open-source-licensing/)

> You're under no obligation to choose a license. It's your right not to include one with your code or project, but please be aware of the implications. Generally speaking, the absence of a license means that the default copyright laws apply. This means that you retain all rights to your source code and that nobody else may reproduce, distribute, or create derivative works from your work. This might not be what you intend.

At your convenience please add a license to this repository - thanks!

**Comment by richard-jones** [comment]
Hi @aeksco - the licence is just in https://github.com/CottageLabs/facetview2#copyright-and-license

Is this sufficient for your needs?

**Comment by aeksco** [comment]
@richard-jones Thanks for responding - glad that the repository already has a license defined (and especially glad it's MIT!). 

I'll open a PR with a LICENSE file in it - that way GitHub can automatically detect which license the repository is under and add it to the header of the repo's homepage. (see attached image for example).

<img width="988" alt="screenshot 2017-01-30 12 54 50" src="https://cloud.githubusercontent.com/assets/4616233/22434992/4a322b56-e6ec-11e6-9c2b-4d50fd2f1370.png">
